export const config={runtime:'edge'};
const URL='https://api.groq.com/openai/v1/chat/completions',MODEL='openai/gpt-oss-120b';
const SYSTEM=`Sen BALKIZ Light'sın: Türkçe konuşan, sıcak, dikkatli ve son derece yetkin bir düşünce ortağısın.
- Kullanıcının gerçek hedefini kavra ve doğrudan faydalı sonuca geç.
- Doğal konuş; kalıp girişlerden, gereksiz övgüden ve yapay resmiyetten kaçın.
- Basit isteğe kısa, karmaşık isteğe düzenli ve kapsamlı yanıt ver.
- Küçük belirsizlikte makul varsayımı söyleyip ilerle; sonucu ciddi değiştirecekse tek net soru sor.
- Önceki mesajlardaki ayrıntıları tutarlı kullan. Bilmediğini açıkça söyle, uydurma.
- Kodda bütünlüklü ve çalışır örnek ver. Markdown'ı yalnızca okunurluğu artırdığında kullan.
- Etkinlik planlarında hedef, yaş grubu, süre, görev dağılımı, gerekli malzemeler ve uygulanabilir akış üret.
- Ürün geliştirmede problemi, hedef kullanıcıyı, temel özellikleri, riskleri ve küçük bir sonraki adımı netleştir.
- Çocuklara yönelik deneylerde yaş uygunluğunu gözet; yetişkin gözetimi, alerji, elektrik, ısı, kesici araç ve kimyasal risklerini açıkça belirt. Tehlikeli uygulamalar yerine güvenli alternatif öner.
- Çocuklara anlatırken küçümseyici konuşma; kısa cümleler, somut örnekler ve merak uyandıran bir dil kullan.
- Kullanıcının dilini takip et; Türkçen doğal, samimi ve profesyonel olsun.`;
const limits=new Map();function limited(ip){const n=Date.now(),x=limits.get(ip);if(!x||n-x.at>60000){limits.set(ip,{at:n,count:1});return false}return++x.count>20}function cors(o){return{'Access-Control-Allow-Origin':o||'*','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin'}}function json(x,s,o){return new Response(JSON.stringify(x),{status:s,headers:{...cors(o),'Content-Type':'application/json'}})}
export default async function handler(req){const origin=req.headers.get('origin')||'*';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(req.method!=='POST')return json({error:'Yalnızca POST destekleniyor.'},405,origin);const ip=req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';if(limited(ip))return json({error:'Çok hızlı gidiyoruz; bir dakika sonra tekrar deneyin.'},429,origin);const key=process.env.GROQ_API_KEY;if(!key)return json({error:'GROQ_API_KEY sunucuda tanımlı değil.'},500,origin);let body;try{body=await req.json()}catch{return json({error:'Geçersiz JSON.'},400,origin)}const messages=(Array.isArray(body?.messages)?body.messages:[]).filter(m=>['user','assistant'].includes(m?.role)&&typeof m.content==='string'&&m.content.trim()).slice(-30).map(m=>({role:m.role,content:m.content.slice(0,16000)}));if(!messages.length||messages.at(-1).role!=='user')return json({error:'Geçerli bir kullanıcı mesajı gerekli.'},400,origin);if(messages.reduce((n,m)=>n+m.content.length,0)>120000)return json({error:'Sohbet çok uzun; yeni bir sohbet başlatın.'},413,origin);let up;try{up=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:MODEL,messages:[{role:'system',content:SYSTEM},...messages],temperature:.55,top_p:.9,max_tokens:4096,stream:true}),signal:req.signal})}catch{return json({error:'Yapay zekâ servisine ulaşılamıyor.'},502,origin)}if(!up.ok||!up.body)return json({error:up.status===429?'Servis yoğun; biraz sonra tekrar deneyin.':'Yapay zekâ servisi yanıt veremedi.'},up.status===429?429:502,origin);const reader=up.body.getReader(),dec=new TextDecoder(),enc=new TextEncoder();const stream=new ReadableStream({async start(c){let buf='',closed=false,send=x=>c.enqueue(enc.encode(`data: ${JSON.stringify(x)}\n\n`));try{while(true){const z=await reader.read();buf+=dec.decode(z.value||new Uint8Array(),{stream:!z.done});const lines=buf.split('\n');buf=lines.pop()||'';for(const line of lines){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(raw==='[DONE]'){send({done:true});c.close();closed=true;return}try{const d=JSON.parse(raw),delta=d?.choices?.[0]?.delta?.content;if(delta)send({delta})}catch{}}if(z.done)break}if(!closed){send({done:true});c.close()}}catch{if(!closed){send({error:'Yanıt akışı kesildi.'});c.close()}}finally{reader.releaseLock()}}});return new Response(stream,{headers:{...cors(origin),'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','X-Accel-Buffering':'no'}})}
